### ISSUE TITLE
doesn't work with HTTP, please change docu

### ISSUE THREAD

**Issue by gitunit** [googlecodelabs/model-viewer-codelab#1]
i've tested the codelab and never got the AR mode to run. codelab mentions to serve the web app with "npm serve" but this only serves sites via HTTP and then you never get AR to see in action. solution is to use HTTPS. im not sure if there is a npm package for that, i doubt it, since you need a certificate etc. 
a very simple solution would be to still use "npm serve" but then tunnel the localhost to a public address via something like [NGROK](https://ngrok.com/). they offer tunnels via HTTP and HTTPS as well. so here you have it, less headaches for future coders.

**Comment by smalls** [comment]
Thanks for the feedback! I'll add a note to the codelab.

**Comment by gitunit** [comment]
after almost a whole month nothing has changed (see [here](https://codelabs.developers.google.com/codelabs/model-viewer/index.html?index=..%2F..io2019#1)), i know you must be busy with lots of other stuff but don't you want happy users? its only one or two sentences ;-)

**Comment by gitunit** [comment]
1 year later nothing happened. closing because i don't care either anymore.
