### ISSUE TITLE
expectations for unstable-webxr tag

### ISSUE THREAD

**Issue by gitunit** [googlecodelabs/model-viewer-codelab#2]
what can we expect when using devices without arcore/kit with the "unstable-webxr" tag? is there anything we can see in AR with this or is this not working at all? i've tested with chrome canary (all webxr flags enabled) but still all i could get was only the fullscreen model view but no AR. maybe the current access to the latest WebXR apis are not up to date? (i know its unstable but would be interesting to know what the issue is in this case)

**Comment by gitunit** [comment]
i think i might have found the answer, please correct me if i'm wrong. it works only with "Chrome Canary/Dev versions 70-72", right?

**Comment by smalls** [comment]
That's right, only with those versions of Canary (with WebXR flags enabled, and with the origin trial enabled). 

The model-viewer documentation has a bit more info, and a look to the WebXR codelab: https://googlewebcomponents.github.io/model-viewer/examples/augmented-reality.html
